name: build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.16.2

      - name: Build linux amd64
        run: deno compile envium.ts --allow-env --allow-read --allow-write -o envium_linux_amd64 --target x86_64-unknown-linux-gnu

      - name: Build windows amd64
        run: deno compile envium.ts --allow-env --allow-read --allow-write -o envium_windows_amd64.exe --target x86_64-pc-windows-msvc

      - name: Build darwin amd64
        run: deno compile envium.ts --allow-env --allow-read --allow-write -o envium_darwin_amd64 --target x86_64-apple-darwin

      - name: Build darwin aarch64
        run: deno compile envium.ts --allow-env --allow-read --allow-write -o envium_darwin_aarch64 --target aarch64-apple-darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            envium_linux_amd64
            envium_windows_amd64.exe
            envium_darwin_amd64
            envium_darwin_aarch64
