name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Unit testing
        run: go test ./... -v

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Build Linux AMD64
        run: GOOS=linux GOARCH=amd64 go build -o envium_linux_amd64 cmd/envium/main.go

      - name: Build Windows AMD64
        run: GOOS=windows GOARCH=amd64 go build -o envium_windows_amd64.exe cmd/envium/main.go

      - name: Debug workflow
        run: tree; ls -la

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            envium_linux_amd64
            envium_windows_amd64.exe
            envium_darwin_amd64
            envium_darwin_aarch64
